;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-reader.ss" "lang")((modname |Problem2(solved)|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


; Fibonacci
; Signature: Natural Natural Natural -> (listof Natural)
; Purpose: To make a list of Fibonnaci numbers that start with two given naturals and goes to or less than a limit
;(check-expect (fib 1 1 5) (list 1 1 2 3 5))
(define (fib start1 start2 limit)
  (cond [(>= (+ start1 start2) limit) empty]
        [else (cons (+ start1 start2) (fib start2 (+ start1 start2) limit))]))

(foldl + 0 (filter even? (append (list 1 2 ) (fib 1 2 4000000))))



